### ISSUE TITLE
ThrowingFileFetcher fixture?

### ISSUE THREAD

**Issue by gbirke** [JeroenDeDauw/FileFetcher#6]
What do you think about creating the class `FileFetcher\Tests\Fixtures\ThrowingFileFetcher`? It's only for consumption by users of this library, but it could come in handy. Or should the implementation of that fixture not be done in the library?

**Comment by JeroenDeDauw** [comment]
I think it's good to have this (and other simple and generic test doubles) here, as they are likely useful to users of the library.

**Comment by JeroenDeDauw** [comment]
And it's fine to use PHP 7.0 or 7.1 for this.

**Comment by JeroenDeDauw** [comment]
@gbirke does this fixture already exist somewhere? I thought it did and went looking for it now to include it, but did not find it.

**Comment by gbirke** [comment]
Nope, I just thought it would come in handy for https://github.com/wmde/FundraisingFrontend/pull/878 to get rid of the mock object. Did not write it and used phpunit mock instead.

**Comment by JeroenDeDauw** [comment]
Does constructing a InMemoryFileFetcher with an empty array also do what you want? I think it does. Not sure how to make that easier to find tho.

**Comment by gbirke** [comment]
Yes it does. You could mention it in the README in the usage notes.

**Comment by JeroenDeDauw** [comment]
Yeah. The usage notes are a new thing since 30 min ago :)
